---
title: "Bolivia: datos COVID-19"
author: '**Elaboración**: José Romero      **Fuente**: Ministerio de Salud     **Actualizado**: 26-05-2020'
output: 
  flexdashboard::flex_dashboard:
    logo: "C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\icono3.png"
    vertical_layout: scroll
    orientation: row
    theme: cerulean
---
Column {data-height=110}
-------------------------------------
### 
```{r}
library(dygraphs)
library(readr)
library(tidyverse)
library(xts)
library(plotly)
library(ggthemes)
library(readr)
library(flexdashboard)
library(viridis)
library(hrbrthemes)
library(highcharter)

Conf <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Confirmados.csv", 
                        col_types = cols(`Casos confirmados` = col_integer(), 
                                         Fecha = col_date(format = "%d/%m/%Y")))
valor1 <- max(Conf$`Casos confirmados`, na.rm = FALSE)

valueBox(valor1, caption = "Casos confirmados", color  = '#5B89E2', "icon = fas fa-users")
         
    ```

### 
```{r}

Rec <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Recuperados.csv", 
                        col_types = cols(Fecha = col_date(format = "%d/%m/%Y"), 
                                         Recuperados = col_integer()))
valor2 <- last(Rec$Recuperados, na.rm = FALSE)
valueBox(valor2, caption = "Recuperados", color  = '#00AC37', icon = "glyphicon glyphicon-ok")
    ```

### 
```{r}
Fall <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Fallecidos.csv", 
                       col_types = cols(Fallecidos = col_integer(), 
                                        Fecha = col_date(format = "%d/%m/%Y")))
Valor3 <- last(Fall$Fallecidos, na.rm = FALSE)
valueBox(Valor3, caption = "Decesos", color  = '#8E8E8E', icon = "fas fa-ribbon")
    ```

### 
```{r}
Nuevos_casos_nacional <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Nuevos_casos_nacional.csv", col_types = cols(Fecha = col_date(format = "%d/%m/%Y"),`Nuevos casos` = col_integer()))
View(Nuevos_casos_nacional)

Valor5 <- last(Nuevos_casos_nacional$`Nuevos casos`, na.rm = FALSE)

valueBox(Valor5, caption = "Nuevos casos", color  = '#FFC519', icon = "fas fa-notes-medical")

    ```

Column {data-height=450}
-------------------------------------
### 

```{r}
Nuevos_casos_departamentos <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia/data/Nuevos_casos_departamentos.csv", 
                                       col_types = cols(Fecha = col_date(format = "%d/%m/%Y"), 
                                                        `Nuevos casos` = col_integer()))
                                                
diario <- ggplot(Nuevos_casos_departamentos, aes(Fecha, Departamento, fill=`Nuevos casos`)) + 
  geom_tile() + 
  scale_fill_gradient(low = "#ffffff", high = "#170062")+
  labs(title = 'Nuevos casos de coronavirus por departamento y fecha',
       x= 'Fechas', y ='') +
  theme_calc()+
  theme(legend.position = 'top')


mapa_calor <- ggplotly(diario)%>% config ( displayModeBar  =  F) %>% layout(xaxis=list(fixedrange=TRUE)) %>% 
  layout(yaxis=list(fixedrange=TRUE)) 
mapa_calor

```   

Column 
-------------------------------------
### 
    
```{r}
Nuevos_casos_nacional <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Nuevos_casos_nacional.csv")

barras <- Nuevos_casos_nacional %>% 
hchart(name = 'Nuevos casos', 'column', hcaes(x= 'Fecha', y= `Nuevos casos`)) %>% 
  hc_colors('#5FCAD8') %>% 
hc_plotOptions(column = list(pointWidth= 8)) %>% 
  hc_title(text = "Nuevos casos a nivel nacional por fecha") %>% 
   hc_add_theme(hc_theme_elementary())
barras
  
```

### 
    
```{r}
Confirmados <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Confirmados.csv", 
                        col_types = cols(`Casos confirmados` = col_integer(), 
                                         Fecha = col_date(format = "%d/%m/%Y")))

Fallecidos <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Fallecidos.csv", 
                       col_types = cols(Fallecidos = col_integer(), 
                                        Fecha = col_date(format = "%d/%m/%Y")))

Recuperados <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Recuperados.csv", 
                        col_types = cols(Fecha = col_date(format = "%d/%m/%Y"), 
                                         Recuperados = col_integer()))

Confirmados_xts <- xts(Confirmados$`Casos confirmados`, order.by = Confirmados$Fecha, frequency = 1)

Fallecidos_xts <- xts(Fallecidos$Fallecidos, order.by = Fallecidos$Fecha, frequency = 1)
Recuperados_xts <- xts(Recuperados$Recuperados, order.by = Recuperados$Fecha, frequency = 1)

dinamico <- cbind(Confirmados_xts, Fallecidos_xts, Recuperados_xts)

grafico <- dygraph(dinamico, ylab = 'Cantidad',
                   main = 'Acumulado de casos confirmados, recuperaciones y decesos') %>% 
  dySeries('Confirmados_xts', label = 'Casos') %>% 
  dySeries('Fallecidos_xts', label = 'Fallecidos') %>% 
  dySeries('Recuperados_xts', label = 'Recuperados') %>% 
  dyOptions(colors = c('#0037A2', 'Black', '#00B50C')) %>% 
  dyRangeSelector(height = 20) %>% 
  dyOptions(strokeWidth = 2, pointSize = 5, pointShape = 'circle')
  
  
grafico


```


Column 
-------------------------------------
###
```{r}
Acumulado_departamento <- read_csv('C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Acumulado_departamento.csv', 
    col_types = cols(Beni = col_integer(), 
        Chuquisaca = col_integer(), Cochabamba = col_integer(), 
        `La Paz` = col_integer(), Oruro = col_integer(), 
        Pando = col_integer(), `Potosí` = col_integer(), 
        `Santa Cruz` = col_integer(), Tarija = col_integer()))

Nuevo <- Acumulado_departamento %>% gather('Departamentos', 'Casos', 2:10)

departamentos <- Nuevo %>% 
  hchart('line', hcaes(x='Fecha', y='Casos', group = 'Departamentos')) %>% 
  hc_colors(c('#FF0000', '#800000', '#FFFF00', '#808000', '#008000', '#00FFFF', '#008080', '#000080', '#800080')) %>% 
  hc_title(text = "Acumulado de casos confirmados por departamento") %>% 
 hc_add_theme(hc_theme_smpl())
  
departamentos

```
   

###
```{r}
mapdata <- get_data_from_map(download_map_data('countries/bo/bo-all'))

Lista_de_departamentos <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Lista de departamentos.csv", 
    col_types = cols(`Casos confirmados` = col_integer()))
### La Paz-Cochabamba-Chuquisaca-Beni-Oruro-Potosí-Santa Cruz-Tarija-Pando
'Casos confirmados' <- mapdata %>% 
  select(Departamento = 'name') 
`Casos confirmados`$Casos = c(410, 345, 22, 1242, 153, 44, 4888, 19, 13)

mapa <- hcmap('countries/bo/bo-all', data = `Casos confirmados`,
      joinBy = c("name", "Departamento"), name = "Casos confirmados", value = "Casos",
      dataLabels = list(enabled = F, format = '{point.name}',
      borderColor = "#000000", borderWidth = 0.5)) %>% 
  hc_title(text = "Mapa: cantidad de casos confirmados por departamento") %>% 
  hc_add_theme(hc_theme_elementary()) 
mapa

```

Column 
-------------------------------------
###
```{r}
Registro_departamentos <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\Registro departamentos.csv", 
    col_types = cols(Cantidad = col_integer()))
hchart(Registro_departamentos, "bar", hcaes(x = "Departamento", y = "Cantidad", group = "Tipo")) %>% 
  hc_plotOptions(bar = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal")) %>% 
   hc_title(text = "Registro de casos COVID-19")
```

###
```{r}
municipios <- read_csv("C:\\Users\\Asus\\Documents\\Datos COVID-19 Bolivia\\data\\municipios.csv")

hcmap('countries/bo/bo-all', showInLegend = F) %>%
  hc_add_series(data = municipios, type = "mapbubble", name = "Casos confirmados", maxSize = '18%', color = "orange") %>% 
  hc_mapNavigation(enabled = TRUE) %>% 
  hc_title(text = "Cantidad de casos de COVID-19 por municipio")

```
